### ISSUE TITLE
Deleted a folder that was part of the backup, now I get a couldn't backup error everytime.

### ISSUE THREAD

**Issue by bassamanator** [spersson/Kup#97] opened 2020-05-13 03:32 UTC
So there was a folder that was part of my backup scheme. I deleted it. Now every time I backup, I get an error message because that folder is part of what's supposed to be backed up but that folder doesn't exist anymore.

Obviously when I try to remove that folder from the GUI configuration, it's not there because it doesn't exist. How do I remove that folder from the 'to backup list'? I don't want to create a new backup plan.

Love this app btw!

**Comment by spersson** [comment] 2020-05-22 04:27
Looks like my email reply didn't make it's way to github. I was saying: Thank you for reporting and I will look into this situation. I had never thought of it.
For now, I think it should work to just open the configuration and click save. It should check existance of any folder configured and remove is don't exist. Then detect that current config is not same as saved one. If it doesn't work then perhaps just make some other random change and save.

**Comment by bassamanator** [comment] 2020-05-22 08:20
Yes I found the same solution, edit the plan and hit save.
Thanks!

**Comment by spersson** [comment] 2020-06-07 03:20
I have worked on this issue lately and confirmed that yes, you only need to open settings and then click OK to save the new configuration with non-existing folders removed. I also made a change so that every time a new backup is being saved it will first check that all source folders exist and if not abort the saving and prompt the user to open settings. I did it that way since I suspect that the most common reason for this situation is that a folder has been renamed and then I don't want to just automatically remove something from your settings and carry on without it, better that the user confirms again what to include.
I think that solves this whole thing properly. Will be included in next release, 0.8.1.

**Closed as completed by spersson** 2020-06-07 03:20 UTC
