### ISSUE TITLE
Kup widget shows empty icon

### ISSUE THREAD

**Issue by ylogx** [spersson/Kup#85] opened 2019-08-10 00:02 UTC
Image showing the empty icon with no name above the buttons for each backup in the list:

![IMG_20190809_195910](https://user-images.githubusercontent.com/3508878/62814771-9793d780-bae0-11e9-8ffd-2129a3702f09.jpg)

**Comment by spersson** [comment] 2019-08-28 08:52
Back in february I made release 0.7.3 of kup to fix this problem (which was caused by changes in Qt version 5.12). Please confirm which version of kup you are using. Thanks!

**Comment by spersson** [comment] 2019-11-19 02:53
No reply from reporter, assume issue was solved in latest release. Closing issue.

**Closed by spersson** 2019-11-19 02:53 UTC
