### ISSUE TITLE
bup repository always grows?

### ISSUE THREAD

**Issue by erenoglu** [spersson/Kup#10] opened 2013-11-03 09:23 UTC
Hi,
As far as I understand, the bup repository will always accumulate files even if they were deleted from source and even if they are not wanted anymore. For example, backing up your personal video & pictures. Assume your video were in MPEG2 format and you compressed them to mp4. Now you don't need anymore the MPEG2 versions taking space.

So, is it possible to configure (maybe a feature request) kup that after, say X backups, the last one can be deleted (ie reset & re-do a full backup if needed) so that the git repository is cleaned up?

else, it seems I will need to delete (or rename) the repository manually and then do another backup from scratch.

**Comment by mattiaverga** [comment] 2017-05-01 09:18
Bup has now added experimental support for pruning old backups since a few releases, it would be nice to have this capability added to Kup.

**Comment by spersson** [comment] 2017-05-03 03:11
Yes, I agree. If I get some time for working on kup this is something that could be a very interesting addition. Possibly combined with reading the index file and estimating if it would be worth spending the time re-writing the pack-files. Or something like that. Research needed! :)
Anybody is welcome to help with researching how it could work in detail!

**Comment by HinzundKunz** [comment] 2018-04-19 06:05
I would be very happy to see this happen. I have used one single backup for about five years now, and it has grown to over 500GB, around 100GB of which I would like to get rid of, but I would like to keep the rest.

**Comment by carlonluca** [comment] 2020-03-05 13:01
Anyone with experiences about bup pruning? I was thinking of adding this to Kup, but I keep reading support is experimental and unsafe.

**Comment by carlonluca** [comment] 2020-03-07 14:02
I was thinking about something like this.
![Screenshot_20200307_145901](https://user-images.githubusercontent.com/3678828/76144856-8154f680-6084-11ea-8729-b5c05daa279f.png)

**Comment by carlonluca** [comment] 2020-04-06 05:48
@spersson would you accept patches to include support for pruning?

**Comment by spersson** [comment] 2020-04-06 09:58
Hey @carlonluca, sorry for late reply. I had been meaning to comment on your mockup but then forgot.
Yes, I am open for adding pruning and I like your mockup. Looks good! One concern here could be how well that layout works for languages other than english, since the widgets basically combines to form a sentence. Not sure if it's a problem. Maybe there is an alternative layout and wording that can work. I can look at other backup solutions how they do it.
Another thought: that last combo could be removed right? "Keep yearly for the last x months" doesn't make much sense to me, so the only unit in that combo would be years. Unless you want decades in there. Similarly I expect the monthly combo box to only have months and years as available units.
How to to deal with the situation where none of the check boxes are ticked? That would imply that every snapshot will be removed. For now, the best I can think of is to add one more check box called "keep all snapshots forever" which would be the default selection. When ticking at least one of the other checkboxes this one would automatically untick itself. If later the user unticks all other "keep" checkboxes then the forever box would tick itself again.

Next is about actions. I assume we should run a pruning operation first thing before saving a new snapshot?
So the order would be 

1. prune(if enabled)
2. fsck (if integrity check is enabled. And perhaps also if pruning is enabled? Maybe good to always check since backup files have been rewritten)
3. index
4. save
5. generate recovery data

The advantage would be that you could operate closer to full disk by always removing before adding.

Last thing... development now happens in kde git repo. http://invent.kde.org/kde/kup

**Comment by carlonluca** [comment] 2020-04-06 11:49
> One concern here could be how well that layout works for languages other than english, since the widgets basically combines to form a sentence

Are you referring only to the sentence at the bottom? Actually that would simply be some translated strings separated by a semicolon. Do you think treating each portion separately would be a problem?

> Another thought: that last combo could be removed right? "Keep yearly for the last x months" doesn't make much sense to me

Yes, I agree. I left those there only because it seems bup supports that, but it makes sense to only leave some options. A time unit of seconds for monthly doesn't make sense.

> For now, the best I can think of is to add one more check box called "keep all snapshots forever" which would be the default selection

It seems a good solution to the problem.

> I assume we should run a pruning operation first thing before saving a new snapshot?

This was my first thought. I think it is reasonable.
Then, experimenting a bit with bup pruning, I came to another possible idea. I thought that pruning is a considerably dangerous operation. If someone misunderstood the configuration options or if someone had a wrong time temporarily set in his system, snapshots would be irrecoverably lost, forever. That is a bit scary. So I thought of another option: why not making pruning a "manual" operation? That would allow us to compute first what is going to be done (bup has support for that), present to the user the result, and wait for his confirmation. So we are sure the user is not accidentally erasing the universe. This is a UI proposal.

![Screenshot_20200406_130926](https://user-images.githubusercontent.com/3678828/78554858-31e12200-780c-11ea-88f3-279bbd61cccf.png)

The items selected for removal should have some kind of mark, like an icon. "OK" would actually prune, "cancel" would do nothing, and allow the user to change his options.
What do you think?

> Last thing... development now happens in kde git repo. http://invent.kde.org/kde/kup

Sure. Do you mean just for the code or also for these discussions?

Thank you for your answer.

**Comment by spersson** [comment] 2020-04-09 14:43
Good thinking! I have to admit I had not though about the user accidentaly deleting snapshots. I was mostly thinking of bugs in bup or things like interrupted operations leaving your backup repo in a broken state. 

Now that you got me thinking in this direction... Maybe we could create a new small application, like filedigger, also launched from a button on the plasmoid. Something like this:

![image](https://user-images.githubusercontent.com/1425156/78905160-257cf380-7ab0-11ea-9ec4-03964b47ff0f.png)

If you make this application remember which filter rules you used last then it will be quite convenient to do regular purges, even if it is all "manual". So you can just launch this by clicking "Remove snapshots" in the plasmoid, then this window opens and it has already selected snapshots based on rules used last time for this plan, confirm that it looks correct and then click "delete". The window closes and operation progress is showed in systray notification.

With this option we would not modify the settings module at all. I'm thinking that the convenience of setting the purge rules once and having it done automatically is maybe not worth it. It's not much work to do what I describe above. And some people maybe don't want to do purging of old snapshots every time that they save a new one. What should we do then? Add another setting to say how often to run this purge? Yuck.

One other thing I like about this is that it avoids opening an "unexpected" window. So if you were saving a backup and this window you suggested would pop up, I have a small fear that someone might click OK before even reading at all. I do that all the time with website popups at least! (not sure if that is relevant though... :)

**Comment by carlonluca** [comment] 2020-04-10 05:25
Ok, so a button on the plasmoid should open this new window. Every time the "apply rules" button is pressed, a request is sent to the daemon to compute the tasks to be performed. When the user is happy, settings are saved and a request is sent to the daemon to run the prune. If the deamon is performing a backup, a notification reports to the user to try again after the backup. What do you think?
In the example you provided I see the buttons "select all" and "deselect all". What is their use?

**Comment by spersson** [comment] 2020-04-10 08:46
Maybe I was not clear about my idea... I was thinking that the user can select manually what to delete from a complete list of all snapshots. The "(de)select all" and "apply rules" buttons would just be another way of setting the selection. That way a user can delete exactly which snapshots they want without figuring out a set of "keep" rules that matches what they have in mind.
Of course select all and deselect all are not useful on their own (nobody wants to delete everything I think. And if they want to delete nothing then why is this window open... :) They are just starting points.

When it comes to applying keep rules it can either be done by running a bup command like you said or it can be done internally by our own logic. We then just call bup rm from the daemon with the snapshot dates that has been selected. And then a bup gc to actually reclaim space. And we need to be very clear to the user here that the selected ones are the ones being deleted not the other way around. There is a risk of confusion because the rules are talking about selecting what to keep. We can continue iterating on the design of this UI, my proposal was just a quick sketch.

Sounds good that it is the daemon performing the job, so that the window can close and also like you say.. we can detect ongoing operation and refuse to start a parallell operation on the same repo. So the user clicks "delete" and a request is sent to the daemon. Daemon replies either "OK" and the window can close or it replies with an error which is then shown to the user in a QMessageBox and the window stays open.

**Comment by carlonluca** [comment] 2020-04-11 17:25
Now I understand you mean to select even singularly. While I think this is a reasonable feature to provide (also time machine has it), I have a very small amount of time to provide for this feature. The main need for me here is to have a way to keep the size from only growing.

At this point: the first proposal was to simply set a policy, provide a confirmation step and prune, which can be done with two bup commands. This was the quicker approach I could think of, that could guarantee safety.
Your proposal is to provide a window with a way to list snapshots, select individually, compute entries based on the selected policy etc... and then prune. This is a feature that makes sense, but it is a bit longer to implement, we may need to run multiple commands etc...

What about something in between as a first step? The window shows a UI similar to the one you provided, but I only implement the "keep rules" provided natively by bup. The user can tweak and see the result on the left. Then the user can actually prune, and we should be able to run a single command. If someone wants to add a way to change the selection based on single snapshots, other keep rules etc..., he can add to the existing window we will have, in a second step of the implementation.

Would this be acceptable?

**Comment by spersson** [comment] 2020-04-12 08:16
Yes, absolutely acceptable! Better to have something that covers almost all use cases than to have nothing because we're waiting for someone to have energy for some "perfect" design.

Another thing: I just realized that these "keep rules" gets disabled by choosing 0 for the duration, no need for check boxes. For example in the screenshot I posted it says "keep monthly snapshosts for the last 0 months" which is the same as having monthlies disabled. I don't know if this a good idea, check boxes might be better. It's just something I came to think of...

**Comment by carlonluca** [comment] 2020-04-12 09:17
I had the suspect. But would this be clear for a user?

**Comment by spersson** [comment] 2020-04-13 06:40
No, it may be a simpler interface but not it's perhaps not easier.  Requires more thinking from the user.
In the interest of minimizing number of clicks it might be better to make the default setting for all the numbers and units be something quite reasonable. Like dailies for 1 month, monthlies for 1 year, yearlies for 5 years. Something like that.
Please go ahead and work on this if you have time and motivation. No time pressure at all from my side, take all the time you want. Do you have a KDE developer account?

**Comment by carlonluca** [comment] 2020-04-13 10:05
> Like dailies for 1 month, monthlies for 1 year, yearlies for 5 years

I agree. Exactly what I had in mind.

> Do you have a KDE developer account?

I contributed to KDE products before so I think I have what I need. Should I create a new issue for this in gitlab?

**Comment by carlonluca** [comment] 2020-05-16 07:59
I had a few problems so I had to pause the task. There were bugs in bup that I had to fix and now bup is not even part of Ubuntu anymore. However, this is more or less the UI that will be seen by the user.
![Screenshot_20200516_095543](https://user-images.githubusercontent.com/3678828/82114226-c750c980-975b-11ea-8e7c-160957f6c5fe.png)
Would this be acceptable?

**Comment by spersson** [comment] 2020-05-22 04:30
Hey @carlonluca, sorry for the delay. Busy days for me.
Yes, looks good! Go ahead. I'm getting excited for this!

**Comment by Pointedstick** [comment] 2020-05-22 18:54
Nice! Feel free to submit a merge request: https://invent.kde.org/system/kup/-/merge_requests

**Comment by spersson** [comment] 2021-01-28 04:43
Hello again, @carlonluca! I had some time to work on this while stuck in quarantine. I made a small app like we discussed here, but very minimal to begin with. Just manual selection of which snapshots to remove. I thought that was both easiest to implement and easiest interface for a user to understand. You can see it [here](https://invent.kde.org/system/kup/-/merge_requests/7). If you have time and motivation you are very welcome suggest and work on improvements ot it! Closing this issue since it's basically solved. Improvements or bugs regarding this can be handled in separate issues. Thank you very much to everyone who has commented on this issue!

**Closed by spersson** 2021-01-28 04:43 UTC
Labels: feature suggestion

**Comment by carlonluca** [comment] 2021-01-28 11:43
Hello, I'm sorry but I paused this task months ago mainly for two reasons: ubuntu did not include bup anymore, which I consider relevant, and also because I found huge issues with the bup implementation of pruning in my use case. I sent a few patches to bup about this, but I then found others. Thanks for your work anyway.

**Comment by Satlinker** [comment] 2024-06-06 14:51
Workaround suggestion for deleting old backups:
A "backup enabled" switch should not be for all backups, but for each backup plan individually. So a duplicate of the backup-plan can run, while the older version of this plan is disabled.
So each duplicate plan contains a full backup plus increments of a certain time. Alternatively, a new version of the plan is started when the repository has grown to 200% of its size, for example. User could delete old inactive plans if they wish. Advantage would be that not only one full version would be saved, which would result in a certain redundancy.
