### ISSUE TITLE
Add "borg" as a supported backend

### ISSUE THREAD

**Issue by Sekhemty** [spersson/Kup#63] opened 2018-10-16 10:41 UTC
I'd like to suggest to include "Borg" as a backend for this superb app.

Kup is really well designed and I really like how it integrates with KDE in a discreet but efficient way. I'm currently using "Back in time" as my primary backups solution, but is only supports file-based incremental snapshots, resulting in very large archives and long times.

Now I've tested "Kup" and I'd like to full switch to it, the main problem is that "bup" as a backend means that, AFAIK, it is not possible to set automatic pruning of old backups, at least not in an easy way; borg supports this, while also having other must have features like being chunk-based, supporting compression and encryption, being able to mount the backups to browse the files, and everything else that you can expect from an efficient backup solution.

See the main features in the Quickstart guide: https://borgbackup.readthedocs.io/en/stable/quickstart.html

There is also a third party Python script called "borgmatic" that helps to automatize the whole process by using a config file instead of having to use the CLI parameters: https://torsion.org/borgmatic/ , maybe it could be used as a starting point for kup?

---

I see that a suggestion for using "restic" as a backend was already opened, here is a comparison of these two tools: https://blog.stickleback.dk/borg-or-restic/ , they seem to be rather similar, it seems that borg could be geared more towards a single-pc scenario (due to being faster and more flexible) while restic has features useful in server based backups.

**Comment by spersson** [comment] 2018-10-17 11:46
Thanks for the suggestion, I had never heard of borg before. I also found the following interesting: https://mail.python.org/pipermail/borgbackup/2017q3/000778.html

Closing this as duplicate of #54 . Please help to discuss there! :)

**Closed by spersson** 2018-10-17 11:46 UTC
