### ISSUE TITLE
KUP systray icon and behaviour

### ISSUE THREAD

**Issue by adrfantini** [spersson/Kup#37] opened 2015-09-24 06:51 UTC
Some minor issues with KUP and systray on up to date Kubuntu 15.04:

1) KUP remains visible (under "auto" visibility settings) even though all backups have been performed. If there are no backups to be performed, it should be hidden
2) KUP nothing-to-do icon is very ugly and uninformative
3) KUP backup-to-do icon is the same as Kubuntu's update notifier, so the two create confusion. Also, as stated in another issue thread, KUP notifications and popups are not informative enough of what's going on.
4) When asking to perform a backup, an estimate on the expected length of the process should be included.
5)  When performing a backup, a progress indicator is mandatory.
6) It should be made clear to the user whether it is safe or not to shutdown the system while KUP is doing it's things.

That's intended to be constructive criticism, I love KUP and use it everyday on many systems. Keep up the good job!

Thanks.

**Comment by spersson** [comment] 2015-12-17 12:32
Thanks for the feedback!
I will just quickly respond to your concerns and then close this issue (as it is more of a brain dump than a specific issue...)
1 - That is intentional. It shows up when a backup destination becomes available, by design. But... I also don't like stuff showing up that is of little or no use so I will have a second round of thinking about how it should behave.
2 - Not a very constructive critisism. What information should it convey?
3 - I spent a long time making the icon for Kup. That was enough for me, I'm a programmer. Didn't feel like spending time doing status icons just because some other program could be showing their status with the same icon. Feel free to suggest alternative icons. What more information would you need from notifications?
4 -  This would require doing a lot of scanning which the user never asked for. I personally hate when programs run harddrive scans in the background which I never asked for.
5 - Yeah, my first attempt at submitting code to bup for reporting progress was in 2012. It has still not been discussed much at all, very low interest. I might try again.
6 - Eh, I would think that it is clear even to novice computer users that if you shutdown while copying is in progress, not everything will be copied.

 I do realise my reply here sounds defensive... But actually I am thankful for the suggestions!

**Closed by spersson** 2015-12-17 12:32 UTC

**Comment by adrfantini** [comment] 2015-12-17 14:51
Hi and thanks for the reply. I'll reply point by point, I hope you find my opinion useful.

1 - I honestly hate it when stuff is crowding my tray unnecessarily. I know this may be up to preference, but maybe a config option could be provided. This of course has very low priority.
2 - The icon problem was only related to my arch machine for some reason. It fixed itself after a while.
2bis and 3 - I find notifications should provide as much info as possible, or at least that one can query the icon and get info on remaining time, source, destination, progress, current transfer speed.
4 - Again, config options? Or maybe a "Calculate" button?
5 - This is one of the most important features lacking imho.
6 - You would! I setup KUP to automatically backup all of my mum's data every week, because if it doesn't do it on its own she'll never do it (and she already lost a whole hard drive!). I think this may be a common usage scenario. My mum does not care and does not need to care on when to backup herself, and she most certainly won't remember to check if KUP has finished before shutting down!

Thanks again for KUP, it's brilliant, this is meant to be just constructive criticism! Keep up the good work.
